nick: grrrit-wm
server: irc.freenode.net
userName: lolrrit
realName: GRRRit the Terrible
default-channel: "#wikimedia-dev"
firehose-channel: "#mediawiki-feed"
blacklist:
    L10n-bot
    Jenkins-mwext-sync
channels:
    "#mediawiki-i18n": {
        "mediawiki/extensions/Babel",
        "mediawiki/extensions/CLDR",
        "mediawiki/extensions/ContentTranslation",
        "mediawiki/extensions/Translate",
        "mediawiki/extensions/TranslationNotifications",
        "mediawiki/extensions/TwnMainPage",
        "mediawiki/extensions/UniversalLanguageSelector",
        "translatewiki.*"
        }
    "#mediawiki-parsoid": {
        "mediawiki/services/parsoid",
        "mediawiki/extensions/Parsoid"
        }
    "#mediawiki-visualeditor": {
        "mediawiki/extensions/Cite",
        "mediawiki/extensions/Citoid",
        "mediawiki/extensions/TemplateData",
        "mediawiki/extensions/VisualEditor",
        "mediawiki/extensions/WikiEditor",
        "mediawiki/services/citoid",
        "mediawiki/services/citoid/deploy",
        "oojs/.*",
        "unicodejs",
        "VisualEditor/.*"
        }
    "#pywikibot": {
        "pywikipediabot.*",
        "pywikibot.*"
        }
    "#semantic-mediawiki": {
        "mediawiki/extensions/Semantic.*",
        "mediawiki/extensions/SMW.*",
        "mediawiki/extensions/Ask",
        "mediawiki/extensions/Validator",
        "mediawiki/extensions/Maps",
        "mediawiki/extensions/RDFIO",
        "mediawiki/extensions/SolrStore"
        }
    "#wikimedia-analytics": {
        "analytics/.*"
        }
    "#wikimedia-dev": {
        # These are sent to #wikimedia-corefeatures too
        "mediawiki/extensions/Echo",
        "mediawiki/extensions/Flow",
        "mediawiki/extensions/PageTriage",
        "mediawiki/extensions/Thanks",
        # These are sent to #wikimedia-multimedia too
        "mediawiki/extensions/UploadWizard.*",
        "mediawiki/extensions/TimedMediaHandler.*",
        "mediawiki/extensions/PronunciationRecording",
        # These are sent to #wikimedia-labs too
        "labs/tools/grrrit",
        # These are sent to #wikipedia-en-ambassadors too
        "mediawiki/extensions/Campaigns",
        "mediawiki/extensions/EducationProgram",
        # These are sent to #mediawiki-visualeditor too
        "mediawiki/extensions/Cite",
        "mediawiki/extensions/TemplateData",
        "mediawiki/extensions/WikiEditor",
        # These are sent to #brickimedia too
        "mediawiki/extensions/MediaWikiChat"
        }
    "#wikimedia-fundraising": {
        "mediawiki/extensions/DonationInterface",
        "mediawiki/extensions/CentralNotice",
        "mediawiki/extensions/ContributionTracking",
        "mediawiki/extensions/ContributionReporting",
        "mediawiki/extensions/DonationEmailUnsubscribe",
        "mediawiki/extensions/FundraiserLandingPage",
        "mediawiki/extensions/FundraiserStatistics",
        "wikimedia/fundraising/.*"
        }
    "#wikimedia-corefeatures": {
        "mediawiki/extensions/Echo",
        "mediawiki/extensions/Flow",
        "mediawiki/extensions/PageTriage",
        "mediawiki/extensions/Thanks"
        }
    "#wikimedia-labs": {
        "labs/.*"
        }
    "#wikimedia-mobile": {
        "mediawiki/extensions/MobileFrontend",
        "mediawiki/extensions/ZeroRatedMobileAccess",
        "mediawiki/extensions/JsonConfig",
        "mediawiki/extensions/ZeroBanner",
        "mediawiki/extensions/ZeroPortal",
        "apps/.*"
        }
    "#wikimedia-operations": {
        # Do not post betacluster stuff here
        "operations.*": {
            branch: "^(?!betacluster)"
            },
        "wikimedia/bugzilla/modifications",
        "wikimedia/bots/jouncebot"
        }
    "#wikimedia-qa": {
        "mediawiki/selenium",
        "mediawiki/ruby/.*",
        "integration/.*",
        "mediawiki/tools/codesniffer",
        # All commits to a betacluster branch goes here
        ".*": {
            branch: "betacluster"
            }
        }
    "#wikidata": {
        "mediawiki/extensions/Wikibase.*",
        "mediawiki/extensions/Wikidata.*",
        "mediawiki/extensions/DataTypes",
        "mediawiki/extensions/DataValues.*",
        "mediawiki/extensions/DataValueImplementations",
        "mediawiki/extensions/ValueView",
        "mediawiki/extensions/Capiunto"
        }
    "#wikimedia-growth": {
        "mediawiki/extensions/GuidedTour",
        "mediawiki/extensions/GettingStarted"
        }
    "#wikimedia-multimedia": {
        "mediawiki/extensions/CommonsMetadata.*",
        "mediawiki/extensions/MultimediaViewer.*",
        "mediawiki/extensions/UploadWizard.*",
        "mediawiki/extensions/TimedMediaHandler.*",
        "mediawiki/extensions/PronunciationRecording",
        "mediawiki/extensions/ImageMetrics",
        "analytics/multimedia.*"
        }
    "#wikipedia-en-ambassadors": {
        "mediawiki/extensions/Campaigns",
        "mediawiki/extensions/EducationProgram"
        }
    "#wmt": {
        "labs/tools/WMT"
        }
    "#brickimedia": {
        "mediawiki/extensions/MediaWikiChat"
        }
